from astro_scripts.plot_fits import runner as plot_fits
from astro_scripts.numpy2moog import runner as numpy2moog
from astro_scripts.fitsHeader import main as fitsheader
from astro_scripts.ascii2fits import main as ascii2fits
from astro_scripts.CRIRES2ARES import runner as CRIRES2ARES
from astro_scripts.linelist_filter import main as linelist_filter
from astro_scripts.rv_measure import runner as rv_measure
from astro_scripts.VALDextraction import main as VALDextraction
from astro_scripts.VALDprepare import runner as VALDprepare
from astro_scripts.vizier_query import main as vizier_query
